spring:

    datasource:
        #druid相关配置
        druid:
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/miniprogram_demo?characterEncoding=utf8
          username: root
          #用ConfigFilter加密后的密码
          password: YjUArzgk/LI4QrVXXDF7u9vB1iURwxZtMG53nP9sTONi/xML2NkjklIsjgOukAuZ8DnmG8BaozG9ylqJsaiBlw==
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
          #监控统计拦截的filters
          filters: stat,config
          #开启ConfigFilter解密，并设置RSA公钥
          connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALXzPb4ZCmu5NLcQdiLUdSXy7R9SC+4LJdxeIbEP3InIZU3frf2DQlhc8UuXR/N1yQX+UM8KtAt3z4f/+9psYCcCAwEAAQ==

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wuleshen.miniprogram.demo.entity  # 注意：对应实体类的路径

# 打印mybatis日志
logging:
  level:
    com:
      wuleshen:
        miniprogram:
          demo:
            dao: debug